obj-y	+= fsl_fman_mac.o fsl_mac.o

fsl_fman_mac-objs		:= fman_dtsec.o fman_dtsec_mii_acc.o	\
				   fm_dtsec.o				\
				   fman_memac.o fman_memac_mii_acc.o	\
				   fm_memac.o				\
				   fman_tgec.o fm_tgec.o
fsl_mac-objs += mac.o mac-api.o
