# Common
obj-$(CONFIG_FSL_DPA)				+= dpaa_resource.o

obj-$(CONFIG_FSL_BMAN)				+= bman.o
obj-$(CONFIG_FSL_BMAN_PORTAL)			+= bman-portal.o
bman-portal-y					 = bman_portal.o bman_api.o	\
						   bman_utils.o
