# Common
obj-$(CONFIG_FSL_DPA)				+= dpaa_resource.o

obj-$(CONFIG_FSL_BMAN)				+= bman.o
obj-$(CONFIG_FSL_BMAN_PORTAL)			+= bman-portal.o
bman-portal-y					 = bman_portal.o bman_api.o	\
						   bman_utils.o

obj-$(CONFIG_FSL_QMAN)				+= qman_api.o qman_utils.o qman_driver.o
obj-$(CONFIG_FSL_QMAN_CONFIG)			+= qman.o qman_portal.o
